{{- if .Values.project1Gateway -}}
apiVersion: gateway.networking.io/v1
kind: HTTPRoute
metadata:
  #ex: project1-dev-backend-httproute
  name: {{ include "project1.nameWithEnv" . }}-backend-httproute
  labels:
    {{- include "project1-labels" | nindent 4 }}
    app.kubernetes.io/name: bakend
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: {{ include "project1.name" }}
spec:
  parentRefs:
    - name:  project1-default-gateway
      kind: Gateway
      namespace: project1
  hostnames:
    - "env.project1.com"
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /api/v1
      backendRefs:
        - name: project1-env-backend-service
          port: 8080