apiVersion: v1
kind: Service
metadata:
  name: project1-evn-backend-service
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: project1-backend
    app.kuberenetes.io/part-of: project-1
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: project1-backend
  ports:
    - name: backend 
      port: 8080
      targetPort: 8080