apiVersion: v1
kind: Service
metadata:
  name: {{ include "project1.nameWithEnv" . }}-frontend-service
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ include "project1.nameWithEnv" . }}-frontend-service
    {{- include "project1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: frontend 
    app.kubernetes.io/component: project1-frontend
  ports:
    - name: {{ .Values.frontend.service.portName }}
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}