apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "project1.nameWithEnv" . }}-frontend-deployment
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: project1-frontend
    {{- include "project1.labels" . | nindent 4 }}  
spec:
  replicas: {{ .Values.frontend.deployment.replicas }}

  selector:
    matchLabels:
      app.kubernetes.io/name: frontend 
      app.kubernetes.io/component: project1-frontend

  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
        app.kubernetes.io/component: project1-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend.deployment.imageName.owner }}/{{ .Values.frontend.deployment.imageName.repo }}:{{ .Values.frontend.deployment.imageName.tag }}
          ports:
          ports:
            - name: frontend
              containerPort: {{ .Values.frontend.deployment.container.port }}
              protocol: TCP

          resources:
             {{- toYaml .Values.frontend.deployment.container.resources | nindent 12 }}
          
          startupProbe:
            httpGet:
              path: {{ .Values.frontend.deployment.container.probePath }}
              port: {{ .Values.frontend.deployment.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 5
          
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.deployment.container.probePath }}
              port: {{ .Values.frontend.deployment.container.port }}
            periodSeconds: 5
            failureThreshold: 10
          
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.deployment.container.probePath }}
              port: {{ .Values.frontend.deployment.container.port }}
            periodSeconds: 5
            failureThreshold: 2