apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: project1-default-gateway
  namespace: project1
spec:
  gatewayClassName: nginx
  listeners:
    - hostname: "*.project1.com"
      name: http
      protocol: HTTP
      port: 80
      allowdRoutes:
        namespaces:
          from: All
      